# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hyperliquid.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hyperliquid.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11hyperliquid.proto\x12\x19hyperliquid_l1_gateway.v1\"\x1e\n\tTimestamp\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\"\x15\n\x05\x42lock\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"!\n\x11OrderBookSnapshot\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1a\n\nBlockFills\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\xb9\x03\n\x14HyperLiquidL1Gateway\x12l\n\x14GetOrderBookSnapshot\x12$.hyperliquid_l1_gateway.v1.Timestamp\x1a,.hyperliquid_l1_gateway.v1.OrderBookSnapshot\"\x00\x12Z\n\x0cStreamBlocks\x12$.hyperliquid_l1_gateway.v1.Timestamp\x1a .hyperliquid_l1_gateway.v1.Block\"\x00\x30\x01\x12r\n\x18StreamOrderBookSnapshots\x12$.hyperliquid_l1_gateway.v1.Timestamp\x1a,.hyperliquid_l1_gateway.v1.OrderBookSnapshot\"\x00\x30\x01\x12\x63\n\x10StreamBlockFills\x12$.hyperliquid_l1_gateway.v1.Timestamp\x1a%.hyperliquid_l1_gateway.v1.BlockFills\"\x00\x30\x01\x42\x0eZ\x0cinternal/apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hyperliquid_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\014internal/api'
  _globals['_TIMESTAMP']._serialized_start=48
  _globals['_TIMESTAMP']._serialized_end=78
  _globals['_BLOCK']._serialized_start=80
  _globals['_BLOCK']._serialized_end=101
  _globals['_ORDERBOOKSNAPSHOT']._serialized_start=103
  _globals['_ORDERBOOKSNAPSHOT']._serialized_end=136
  _globals['_BLOCKFILLS']._serialized_start=138
  _globals['_BLOCKFILLS']._serialized_end=164
  _globals['_HYPERLIQUIDL1GATEWAY']._serialized_start=167
  _globals['_HYPERLIQUIDL1GATEWAY']._serialized_end=608
# @@protoc_insertion_point(module_scope)
