# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import hyperliquid_pb2 as hyperliquid__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hyperliquid_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HyperLiquidL1GatewayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOrderBookSnapshot = channel.unary_unary(
                '/hyperliquid_l1_gateway.v1.HyperLiquidL1Gateway/GetOrderBookSnapshot',
                request_serializer=hyperliquid__pb2.Timestamp.SerializeToString,
                response_deserializer=hyperliquid__pb2.OrderBookSnapshot.FromString,
                _registered_method=True)
        self.StreamBlocks = channel.unary_stream(
                '/hyperliquid_l1_gateway.v1.HyperLiquidL1Gateway/StreamBlocks',
                request_serializer=hyperliquid__pb2.Timestamp.SerializeToString,
                response_deserializer=hyperliquid__pb2.Block.FromString,
                _registered_method=True)
        self.StreamOrderBookSnapshots = channel.unary_stream(
                '/hyperliquid_l1_gateway.v1.HyperLiquidL1Gateway/StreamOrderBookSnapshots',
                request_serializer=hyperliquid__pb2.Timestamp.SerializeToString,
                response_deserializer=hyperliquid__pb2.OrderBookSnapshot.FromString,
                _registered_method=True)
        self.StreamBlockFills = channel.unary_stream(
                '/hyperliquid_l1_gateway.v1.HyperLiquidL1Gateway/StreamBlockFills',
                request_serializer=hyperliquid__pb2.Timestamp.SerializeToString,
                response_deserializer=hyperliquid__pb2.BlockFills.FromString,
                _registered_method=True)


class HyperLiquidL1GatewayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetOrderBookSnapshot(self, request, context):
        """Get single OrderBookSnapshot at timestamp
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamBlocks(self, request, context):
        """Stream Blocks starting from timestamp
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamOrderBookSnapshots(self, request, context):
        """Stream OrderBookSnapshots starting from timestamp
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamBlockFills(self, request, context):
        """Stream BlockFills starting from timestamp
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HyperLiquidL1GatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOrderBookSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderBookSnapshot,
                    request_deserializer=hyperliquid__pb2.Timestamp.FromString,
                    response_serializer=hyperliquid__pb2.OrderBookSnapshot.SerializeToString,
            ),
            'StreamBlocks': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamBlocks,
                    request_deserializer=hyperliquid__pb2.Timestamp.FromString,
                    response_serializer=hyperliquid__pb2.Block.SerializeToString,
            ),
            'StreamOrderBookSnapshots': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamOrderBookSnapshots,
                    request_deserializer=hyperliquid__pb2.Timestamp.FromString,
                    response_serializer=hyperliquid__pb2.OrderBookSnapshot.SerializeToString,
            ),
            'StreamBlockFills': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamBlockFills,
                    request_deserializer=hyperliquid__pb2.Timestamp.FromString,
                    response_serializer=hyperliquid__pb2.BlockFills.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hyperliquid_l1_gateway.v1.HyperLiquidL1Gateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hyperliquid_l1_gateway.v1.HyperLiquidL1Gateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HyperLiquidL1Gateway(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetOrderBookSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperliquid_l1_gateway.v1.HyperLiquidL1Gateway/GetOrderBookSnapshot',
            hyperliquid__pb2.Timestamp.SerializeToString,
            hyperliquid__pb2.OrderBookSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamBlocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hyperliquid_l1_gateway.v1.HyperLiquidL1Gateway/StreamBlocks',
            hyperliquid__pb2.Timestamp.SerializeToString,
            hyperliquid__pb2.Block.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamOrderBookSnapshots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hyperliquid_l1_gateway.v1.HyperLiquidL1Gateway/StreamOrderBookSnapshots',
            hyperliquid__pb2.Timestamp.SerializeToString,
            hyperliquid__pb2.OrderBookSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamBlockFills(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hyperliquid_l1_gateway.v1.HyperLiquidL1Gateway/StreamBlockFills',
            hyperliquid__pb2.Timestamp.SerializeToString,
            hyperliquid__pb2.BlockFills.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
